package projectBloodKart;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/log1")
public class Login extends HttpServlet {
	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
		try {
			PrintWriter pw = res.getWriter();
			
			Class.forName("oracle.jdbc.driver.OracleDriver");
			Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shinchan");

			String s1 = req.getParameter("name");
			String s2 = req.getParameter("pwd");

			PreparedStatement ps = con.prepareStatement("SELECT * FROM REGISTER WHERE NAME = ? AND PWD = ?");

			ps.setString(1, s1);
			ps.setString(2, s2);

			int k = ps.executeUpdate();
			
			if(k!=0) pw.print("<!doctype html>\r\n"
					+ "<html class=\"no-js\" lang=\"zxx\">\r\n"
					+ "    <head>\r\n"
					+ "        <!-- Meta Tags -->\r\n"
					+ "		<meta charset=\"utf-8\">\r\n"
					+ "		<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
					+ "		<meta name=\"keywords\" content=\"Site keywords here\">\r\n"
					+ "		<meta name=\"description\" content=\"\">\r\n"
					+ "		<meta name='copyright' content=''>\r\n"
					+ "		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n"
					+ "		\r\n"
					+ "		<!-- Title -->\r\n"
					+ "        <title>BloodKart | BloodKart Donor & Utilities</title>\r\n"
					+ "		\r\n"
					+ "		<!-- Favicon -->\r\n"
					+ "        <link rel=\"icon\" href=\"img/favicon.png\">\r\n"
					+ "		\r\n"
					+ "		<!-- Google Fonts -->\r\n"
					+ "		<link href=\"https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap\" rel=\"stylesheet\">\r\n"
					+ "\r\n"
					+ "		<!-- Bootstrap CSS -->\r\n"
					+ "		<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n"
					+ "		<!-- Nice Select CSS -->\r\n"
					+ "		<link rel=\"stylesheet\" href=\"css/nice-select.css\">\r\n"
					+ "		<!-- Font Awesome CSS -->\r\n"
					+ "        <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n"
					+ "		<!-- icofont CSS -->\r\n"
					+ "        <link rel=\"stylesheet\" href=\"css/icofont.css\">\r\n"
					+ "		<!-- Slicknav -->\r\n"
					+ "		<link rel=\"stylesheet\" href=\"css/slicknav.min.css\">\r\n"
					+ "		<!-- Owl Carousel CSS -->\r\n"
					+ "        <link rel=\"stylesheet\" href=\"css/owl-carousel.css\">\r\n"
					+ "		<!-- Datepicker CSS -->\r\n"
					+ "		<link rel=\"stylesheet\" href=\"css/datepicker.css\">\r\n"
					+ "		<!-- Animate CSS -->\r\n"
					+ "        <link rel=\"stylesheet\" href=\"css/animate.min.css\">\r\n"
					+ "		<!-- Magnific Popup CSS -->\r\n"
					+ "        <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n"
					+ "		\r\n"
					+ "		<!-- Medipro CSS -->\r\n"
					+ "        <link rel=\"stylesheet\" href=\"css/normalize.css\">\r\n"
					+ "        <link rel=\"stylesheet\" href=\"style.css\">\r\n"
					+ "        <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n"
					+ "		\r\n"
					+ "    </head>\r\n"
					+ "	\r\n"
					+ "	<style>\r\n"
					+ "	</style>	\r\n"
					+ "		\r\n"
					+ "    <body>\r\n"
					+ "	\r\n"
					+ "		<!-- Preloader -->\r\n"
					+ "        <div class=\"preloader\">\r\n"
					+ "            <div class=\"loader\">\r\n"
					+ "                <div class=\"loader-outter\"></div>\r\n"
					+ "                <div class=\"loader-inner\"></div>\r\n"
					+ "\r\n"
					+ "                <div class=\"indicator\"> \r\n"
					+ "                    <svg width=\"16px\" height=\"12px\">\r\n"
					+ "                        <polyline id=\"back\" points=\"1 6 4 6 6 11 10 1 12 6 15 6\"></polyline>\r\n"
					+ "                        <polyline id=\"front\" points=\"1 6 4 6 6 11 10 1 12 6 15 6\"></polyline>\r\n"
					+ "                    </svg>\r\n"
					+ "                </div>\r\n"
					+ "            </div>\r\n"
					+ "        </div>\r\n"
					+ "        \r\n"
					+ "		<!-- Header Area -->\r\n"
					+ "		<header class=\"header\" >\r\n"
					+ "			<!-- Topbar -->\r\n"
					+ "			<div class=\"topbar\">\r\n"
					+ "				<div class=\"container\">\r\n"
					+ "					<div class=\"row\">\r\n"
					+ "						<div class=\"col-lg-6 col-md-5 col-12\">\r\n"
					+ "							<!-- Contact -->\r\n"
					+ "							<ul class=\"top-link\">\r\n"
					+ "								<li><a href=\"#\">About</a></li>\r\n"
					+ "								<li><a href=\"#\">Contact</a></li>\r\n"
					+ "								<li><a href=\"#\">FAQ</a></li>\r\n"
					+ "							</ul>\r\n"
					+ "							<!-- End Contact -->\r\n"
					+ "						</div>\r\n"
					+ "						<div class=\"col-lg-6 col-md-7 col-12\">\r\n"
					+ "							<!-- Top Contact -->\r\n"
					+ "							<ul class=\"top-contact\">\r\n"
					+ "								<li><i class=\"fa fa-phone\"></i>+91 1234 56789</li>\r\n"
					+ "								<li><i class=\"fa fa-envelope\"></i><a href=\"mailto:support@yourmail.com\">BloodKart@hospital.com</a></li>\r\n"
					+ "							</ul>\r\n"
					+ "							<!-- End Top Contact -->\r\n"
					+ "						</div>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "			</div>\r\n"
					+ "			<!-- End Topbar -->\r\n"
					+ "			<!-- Header Inner -->\r\n"
					+ "			<div class=\"header-inner\">\r\n"
					+ "				<div class=\"container\">\r\n"
					+ "					<div class=\"inner\">\r\n"
					+ "						<div class=\"row\">\r\n"
					+ "							<div class=\"col-lg-3 col-md-3 col-12\">\r\n"
					+ "								<!-- Start Logo -->\r\n"
					+ "								<div class=\"logo\">\r\n"
					+ "									<a href=\"index.html\"><img src=\"img/logo.png\" alt=\"#\"></a>\r\n"
					+ "								</div>\r\n"
					+ "								<!-- End Logo -->\r\n"
					+ "								<!-- Mobile Nav -->\r\n"
					+ "								<div class=\"mobile-nav\"></div>\r\n"
					+ "								<!-- End Mobile Nav -->\r\n"
					+ "							</div>\r\n"
					+ "							<div class=\"col-lg-7 col-md-9 col-12\">\r\n"
					+ "								<!-- Main Menu -->\r\n"
					+ "								<div class=\"main-menu\">\r\n"
					+ "									<nav class=\"navigation\">\r\n"
					+ "										<ul class=\"nav menu\">\r\n"
					+ "											<li class=\"active\"><a href=\"index.html\">Home <!-- <i class=\"icofont-rounded-down\"></i>--></a> \r\n"
					+ "												<!-- <ul class=\"dropdown\">\r\n"
					+ "													<li><a href=\"index.html\">Home Page 1</a></li>\r\n"
					+ "												</ul> -->\r\n"
					+ "											</li>\r\n"
					+ "											<li><a href=\"blog-single.html\">Blogs</a>\r\n"
					+ "											</li>\r\n"
					+ "											<li><a href=\"contact.html\">Contact Us</a></li>\r\n"
					+ "										</ul>\r\n"
					+ "									</nav>\r\n"
					+ "								</div>\r\n"
					+ "								<!--/ End Main Menu -->\r\n"
					+ "							</div>\r\n"
					+ "							<div class=\"col-lg-2 col-12\">\r\n"
					+ "								<div class=\"get-quote\">\r\n"
					+ "									<a href=\"Login.html\" class=\"btn\">"+s1+"</a>\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "						</div>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "			</div>\r\n"
					+ "			<!--/ End Header Inner -->\r\n"
					+ "		</header>\r\n"
					+ "		<!-- End Header Area -->\r\n"
					+ "		\r\n"
					+ "		<!-- Slider Area -->\r\n"
					+ "		<section class=\"slider\">\r\n"
					+ "			<div class=\"hero-slider\">\r\n"
					+ "				<!-- Start Single Slider -->\r\n"
					+ "				<div class=\"single-slider\" style=\"background-image:url('img/bk.avif')\">\r\n"
					+ "					<div class=\"container\">\r\n"
					+ "						<div class=\"row\">\r\n"
					+ "							<div class=\"col-lg-7\">\r\n"
					+ "								<div class=\"text\">\r\n"
					+ "									<h1>We Provide <span>BloodKart</span> Services That You Can <span>Trust!</span></h1>\r\n"
					+ "									<p>To give blood you need neither extra strength nor extra food, and you will save a life. </p>\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "						</div>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "				<!-- End Single Slider -->\r\n"
					+ "				<!-- Start Single Slider -->\r\n"
					+ "				<div class=\"single-slider\" style=\"background-image:url('img/slider.jpg')\">\r\n"
					+ "					<div class=\"container\">\r\n"
					+ "						<div class=\"row\">\r\n"
					+ "							<div class=\"col-lg-7\">\r\n"
					+ "								<div class=\"text\">\r\n"
					+ "									<h1>We Provide <span>BloodKart</span> Services That You Can <span>Trust!</span></h1>\r\n"
					+ "									<p>A single pint can save three lives, a single gesture can create a million smiles. </p>\r\n"
					+ "									<!-- <div class=\"button\">\r\n"
					+ "										<a href=\"#\" class=\"btn\">Get Appointment</a>\r\n"
					+ "										<a href=\"#\" class=\"btn primary\">About Us</a>\r\n"
					+ "									</div> -->\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "						</div>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "				<!-- Start End Slider -->\r\n"
					+ "				<!-- Start Single Slider -->\r\n"
					+ "				<div class=\"single-slider\" style=\"background-image:url('img/slider3.jpg')\">\r\n"
					+ "					<div class=\"container\">\r\n"
					+ "						<div class=\"row\">\r\n"
					+ "							<div class=\"col-lg-7\">\r\n"
					+ "								<div class=\"text\">\r\n"
					+ "									<h1>We Provide <span>BloodKart</span> Services That You Can <span>Trust!</span></h1>\r\n"
					+ "									<p>Heroes come in all types and sizes, but the most important are the ones who save lives—like blood donors. </p>\r\n"
					+ "									<!-- <div class=\"button\">\r\n"
					+ "										<a href=\"#\" class=\"btn\">Get Appointment</a>\r\n"
					+ "										<a href=\"#\" class=\"btn primary\">Contact Now</a>\r\n"
					+ "									</div> -->\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "						</div>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "				<!-- End Single Slider -->\r\n"
					+ "			</div>\r\n"
					+ "		</section>\r\n"
					+ "		<!--/ End Slider Area -->\r\n"
					+ "		\r\n"
					+ "		<!-- Start Schedule Area -->\r\n"
					+ "		<section class=\"schedule\">\r\n"
					+ "			<div class=\"container\">\r\n"
					+ "				<div class=\"schedule-inner\">\r\n"
					+ "					<div class=\"row\">\r\n"
					+ "						<div class=\"col-lg-4 col-md-6 col-12 \">\r\n"
					+ "							<!-- single-schedule -->\r\n"
					+ "							<div class=\"single-schedule first\">\r\n"
					+ "								<div class=\"inner\">\r\n"
					+ "									<div class=\"icon\">\r\n"
					+ "										<i class=\"fa fa-ambulance\"></i>\r\n"
					+ "									</div>\r\n"
					+ "									<div class=\"single-content\">\r\n"
					+ "										<span>Share your blood.</span>\r\n"
					+ "										<h4>Blood Emergency</h4>\r\n"
					+ "										<p>The blood you donate gives someone another chance at life. One day, that someone may be a close relative, a friend, a loved one—or even you.</p>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "						</div>\r\n"
					+ "						<div class=\"col-lg-4 col-md-6 col-12\">\r\n"
					+ "							<!-- single-schedule -->\r\n"
					+ "							<div class=\"single-schedule middle\">\r\n"
					+ "								<div class=\"inner\">\r\n"
					+ "									<div class=\"icon\">\r\n"
					+ "										<i class=\"icofont-prescription\"></i>\r\n"
					+ "									</div>\r\n"
					+ "									<div class=\"single-content\">\r\n"
					+ "										<span>Give hope.</span>\r\n"
					+ "										<h4>Hospital Utilities</h4>\r\n"
					+ "										<p>Healing begins with a spotless environment. We ensure every corner is clean, making health and safety our ultimate priority.</p>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "						</div>\r\n"
					+ "						<div class=\"col-lg-4 col-md-12 col-12\">\r\n"
					+ "							<!-- single-schedule -->\r\n"
					+ "							<div class=\"single-schedule last\">\r\n"
					+ "								<div class=\"inner\">\r\n"
					+ "									<div class=\"icon\">\r\n"
					+ "										<i class=\"icofont-ui-clock\"></i>\r\n"
					+ "									</div>\r\n"
					+ "									<div class=\"single-content\">\r\n"
					+ "										<span>Be a hero.</span>\r\n"
					+ "										<h4>Organ Donor</h4>\r\n"
					+ "										<p>Becoming an organ donor means giving the ultimate gift—life. Your legacy will live on in the hearts of those you save. Make a difference beyond your lifetime.</p>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "						</div>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "			</div>\r\n"
					+ "		</section>\r\n"
					+ "		\r\n"
					+ "		\r\n"
					+ "		\r\n"
					+ "		<!-- Table -->\r\n"
					+ "		<section class=\"appointment\">\r\n"
					+ "			<div class=\"container\">\r\n"
					+ "				<div class=\"row\">\r\n"
					+ "					<div class=\"col-lg-12\">\r\n"
					+ "						<div class=\"section-title\">\r\n"
					+ "							<h2>We Are Always Ready to Help You. Please Fill the Form.</h2>\r\n"
					+ "							<img src=\"img/section-img.png\" alt=\"#\">\r\n"
					+ "							<p>A patient registration form should include sections for personal details </p>\r\n"
					+ "						</div>\r\n"
					+ "						<h3>Blood Emergency Form</h3>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "				<div class=\"row\">\r\n"
					+ "					<div class=\"col-lg-6 col-md-12 col-12\">\r\n"
					+ "						<form class=\"form\" action=\"blood\" method=\"post\">\r\n"
					+ "							<div class=\"row\">\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "        <select name=\"bloodtype\" required>\r\n"
					+ "                <option value=\"\" disabled selected>Select Blood Group</option>\r\n"
					+ "                <option value=\"A+\">A+</option>\r\n"
					+ "                <option value=\"A-\">A-</option>\r\n"
					+ "                <option value=\"B+\">B+</option>\r\n"
					+ "                <option value=\"B-\">B-</option>\r\n"
					+ "                <option value=\"AB+\">AB+</option>\r\n"
					+ "                <option value=\"AB-\">AB-</option>\r\n"
					+ "                <option value=\"O+\">O+</option>\r\n"
					+ "                <option value=\"O-\">O-</option>\r\n"
					+ "         </select>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										<input name=\"mail\" type=\"email\" placeholder=\"Email\"required>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										<input name=\"phn\" type=\"text\" placeholder=\"Phone\"required>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "			<select name=\"location\" required>\r\n"
					+ "				 <option value=\"locations\">Select Locations</option>\r\n"
					+ "                <option value=\"Ameerpet\">Ameerpet</option>\r\n"
					+ "                <option value=\"Durgam Cheruvu\">Durgam Cheruvu</option>\r\n"
					+ "                <option value=\"Madhapur\">Madhapur</option>\r\n"
					+ "                <option value=\"Kondapur\">Kondapur</option>\r\n"
					+ "                <option value=\"hitech city\">hitech city</option>\r\n"
					+ "            </select>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "							<div class=\"row\">\r\n"
					+ "								<div class=\"col-lg-5 col-md-4 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										<div class=\"button\">\r\n"
					+ "											<button type=\"submit\" class=\"btn\">Submit</button>\r\n"
					+ "										</div>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								<div class=\"button\">\r\n"
					+ "									<button type=\"reset\" class=\"btn\">Reset</button>\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "						</form>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "			</div>\r\n"
					+ "		</section>\r\n"
					+ "		<!--/ End Table -->\r\n"
					+ "		\r\n"
					+ "		<!-- Start Appointment -->\r\n"
					+ "		<section class=\"appointment\">\r\n"
					+ "			<div class=\"container\">\r\n"
					+ "				<div class=\"row\">\r\n"
					+ "					<div class=\"col-lg-12\">\r\n"
					+ "						<div class=\"section-title\">\r\n"
					+ "							<h2>We Are Always Ready to Help You. Please Fill the Form.</h2>\r\n"
					+ "							<img src=\"img/section-img.png\" alt=\"#\">\r\n"
					+ "							<p>A patient registration form should include sections for personal details </p>\r\n"
					+ "						</div>\r\n"
					+ "						<h3>Patient Form</h3>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "				<div class=\"row\">\r\n"
					+ "					<div class=\"col-lg-6 col-md-12 col-12\">\r\n"
					+ "						<form action=\"patient\" method=\"post\">\r\n"
					+ "							<div class=\"row\">\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										<input name=\"name\" type=\"text\" placeholder=\"Name\" required>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										<input name=\"age\" type=\"number\" placeholder=\"Age\" min=\"18\" max=\"60\" required>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										\r\n"
					+ "											<select name=\"gender\" required>\r\n"
					+ "				 <option value=\"Gender\">Select Gender</option>\r\n"
					+ "                <option value=\"male\">Male</option>\r\n"
					+ "                <option value=\"female\">Female</option>\r\n"
					+ "                <option value=\"others\">Others</option>\r\n"
					+ "                \r\n"
					+ "            </select>\r\n"
					+ "										\r\n"
					+ "						\r\n"
					+ "										\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										\r\n"
					+ "		<select name=\"bloodgroup\" required>\r\n"
					+ "                <option value=\"\" disabled selected>Select Blood Group</option>\r\n"
					+ "                <option value=\"A+\">A+</option>\r\n"
					+ "                <option value=\"A-\">A-</option>\r\n"
					+ "                <option value=\"B+\">B+</option>\r\n"
					+ "                <option value=\"B-\">B-</option>\r\n"
					+ "                <option value=\"AB+\">AB+</option>\r\n"
					+ "                <option value=\"AB-\">AB-</option>\r\n"
					+ "                <option value=\"O+\">O+</option>\r\n"
					+ "                <option value=\"O-\">O-</option>\r\n"
					+ "           </select>\r\n"
					+ "										\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										<input name=\"mail\" type=\"email\" placeholder=\"Email\"required>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										<input name=\"phn\" type=\"text\" placeholder=\"Phone\"required>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								\r\n"
					+ "								<div class=\"col-lg-6 col-md-6 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										\r\n"
					+ "			<select name=\"location\" required>\r\n"
					+ "				 <option value=\"locations\">Select Locations</option>\r\n"
					+ "                <option value=\"Ameerpet\">Ameerpet</option>\r\n"
					+ "                <option value=\"Durgam Cheruvu\">Durgam Cheruvu</option>\r\n"
					+ "                <option value=\"Madhapur\">Madhapur</option>\r\n"
					+ "                <option value=\"Kondapur\">Kondapur</option>\r\n"
					+ "                <option value=\"hitech city\">hitech city</option>\r\n"
					+ "            </select>\r\n"
					+ "										\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "							<div class=\"row\">\r\n"
					+ "								<div class=\"col-lg-5 col-md-4 col-12\">\r\n"
					+ "									<div class=\"form-group\">\r\n"
					+ "										<div class=\"button\">\r\n"
					+ "											<button type=\"submit\" class=\"btn\">Submit</button>\r\n"
					+ "										</div>\r\n"
					+ "									</div>\r\n"
					+ "								</div>\r\n"
					+ "								<div class=\"button\">\r\n"
					+ "									<button type=\"reset\" class=\"btn\">Reset</button>\r\n"
					+ "								</div>\r\n"
					+ "							</div>\r\n"
					+ "						</form>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "			</div>\r\n"
					+ "		</section>\r\n"
					+ "		<!-- End Appointment -->\r\n"
					+ "		\r\n"
					+ "		<!-- Footer Area -->\r\n"
					+ "		<footer id=\"footer\" class=\"footer \">\r\n"
					+ "			<!-- Footer Top -->\r\n"
					+ "			<div class=\"footer-top\">\r\n"
					+ "				<div class=\"container\">\r\n"
					+ "					<div class=\"row\">\r\n"
					+ "						<div class=\"col-lg-3 col-md-6 col-12\">\r\n"
					+ "							<div class=\"single-footer\">\r\n"
					+ "								<h2>About Us</h2>\r\n"
					+ "								<p style=\"width: 800px;\">Welcome to BloodKart, your comprehensive solution for life-saving healthcare services including blood emergencies, hospital bed availability (BedKart), and oxygen gas supplies. We are dedicated to taking the guesswork out of critical healthcare decisions, ensuring you and your family receive timely, high-quality care. Our mission is to empower you to make informed healthcare decisions based on reliable information. We strive to make healthcare simpler and more transparent, ensuring you have access to the resources you need during critical times.</p>\r\n"
					+ "								<!-- Social -->\r\n"
					+ "								<ul class=\"social\">\r\n"
					+ "									<li><a href=\"https://www.facebook.com/\"><img src=\"img/facebook.png\" alt=\"\"></a></li>\r\n"
					+ "									<li><a href=\"https://www.instagram.com/\"><img src=\"img/instagram.png\" alt=\"\"></a></li>\r\n"
					+ "									<li><a href=\"https://wa.me/qr/BOWL6K6Q7JT6G1\"><img src=\"img/whatsapp.png\" alt=\"\"></a></li>\r\n"
					+ "									<li><a href=\"https://www.linkedin.com/\"><img src=\"img/linkedin.png\" alt=\"\"></a></li>\r\n"
					+ "									<li><a href=\"https://www.youtube.com/\"><img src=\"img/youtube.png\" alt=\"\"></a></li>\r\n"
					+ "								</ul>\r\n"
					+ "								<!-- End Social -->\r\n"
					+ "							</div>\r\n"
					+ "						</div>\r\n"
					+ "						<div class=\"col-lg-3 col-md-6 col-12\">\r\n"
					+ "\r\n"
					+ "						</div>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "			</div>\r\n"
					+ "			<!--/ End Footer Top -->\r\n"
					+ "			<!-- Copyright -->\r\n"
					+ "			<div class=\"copyright\">\r\n"
					+ "				<div class=\"container\">\r\n"
					+ "					<div class=\"row\">\r\n"
					+ "						<div class=\"col-lg-12 col-md-12 col-12\">\r\n"
					+ "							<div class=\"copyright-content\">\r\n"
					+ "								<p>© Copyright 2018  |  All Rights Reserved by <a href=\"https://www.wpthemesgrid.com\" target=\"_blank\">wpthemesgrid.com</a> </p>\r\n"
					+ "							</div>\r\n"
					+ "						</div>\r\n"
					+ "					</div>\r\n"
					+ "				</div>\r\n"
					+ "			</div>\r\n"
					+ "			<!--/ End Copyright -->\r\n"
					+ "		</footer>\r\n"
					+ "		<!--/ End Footer Area -->\r\n"
					+ "		\r\n"
					+ "		<!-- jquery Min JS -->\r\n"
					+ "        <script src=\"js/jquery.min.js\"></script>\r\n"
					+ "		<!-- jquery Migrate JS -->\r\n"
					+ "		<script src=\"js/jquery-migrate-3.0.0.js\"></script>\r\n"
					+ "		<!-- jquery Ui JS -->\r\n"
					+ "		<script src=\"js/jquery-ui.min.js\"></script>\r\n"
					+ "		<!-- Easing JS -->\r\n"
					+ "        <script src=\"js/easing.js\"></script>\r\n"
					+ "		<!-- Color JS -->\r\n"
					+ "		<script src=\"js/colors.js\"></script>\r\n"
					+ "		<!-- Popper JS -->\r\n"
					+ "		<script src=\"js/popper.min.js\"></script>\r\n"
					+ "		<!-- Bootstrap Datepicker JS -->\r\n"
					+ "		<script src=\"js/bootstrap-datepicker.js\"></script>\r\n"
					+ "		<!-- Jquery Nav JS -->\r\n"
					+ "        <script src=\"js/jquery.nav.js\"></script>\r\n"
					+ "		<!-- Slicknav JS -->\r\n"
					+ "		<script src=\"js/slicknav.min.js\"></script>\r\n"
					+ "		<!-- ScrollUp JS -->\r\n"
					+ "        <script src=\"js/jquery.scrollUp.min.js\"></script>\r\n"
					+ "		<!-- Niceselect JS -->\r\n"
					+ "		<script src=\"js/niceselect.js\"></script>\r\n"
					+ "		<!-- Tilt Jquery JS -->\r\n"
					+ "		<script src=\"js/tilt.jquery.min.js\"></script>\r\n"
					+ "		<!-- Owl Carousel JS -->\r\n"
					+ "        <script src=\"js/owl-carousel.js\"></script>\r\n"
					+ "		<!-- counterup JS -->\r\n"
					+ "		<script src=\"js/jquery.counterup.min.js\"></script>\r\n"
					+ "		<!-- Steller JS -->\r\n"
					+ "		<script src=\"js/steller.js\"></script>\r\n"
					+ "		<!-- Wow JS -->\r\n"
					+ "		<script src=\"js/wow.min.js\"></script>\r\n"
					+ "		<!-- Magnific Popup JS -->\r\n"
					+ "		<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n"
					+ "		<!-- Counter Up CDN JS -->\r\n"
					+ "		<script src=\"http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js\"></script>\r\n"
					+ "		<!-- Bootstrap JS -->\r\n"
					+ "		<script src=\"js/bootstrap.min.js\"></script>\r\n"
					+ "		<!-- Main JS -->\r\n"
					+ "		<script src=\"js/main.js\"></script>\r\n"
					+ "    </body>\r\n"
					+ "</html>");
			
			else
				pw.println("<h1>Invalid Username and Password.</h1>"
						+ "<a href=\"index.html\"><h3>Index</h3></a>");

			
		}

		catch (ClassNotFoundException | SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
}
